---
framework: jest
preRun:
  command:
    - yarn install
preMerge:
  pattern:
    - "scripts/__tests__/*-test.js"
    - "packages/**/__tests__/*.js"
postMerge:
  pattern:
    - "scripts/__tests__/*-test.js"
    - "packages/**/__tests__/*.js"
    - "eslint-rules/__tests__/strictly-null-test.js"
postRun:
  command:
    - yarn --version
version: 1.0
