name: Deploy

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/**"
      - "website/**"
      - ".github/workflows/deploy-website.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.repository == 'facebook/metro'

    env:
      working-directory: website
      node-version: 16.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1.4.5
        with:
          node-version: ${{ env.node-version }}

      - name: Get yarn cache directory
        id: yarn
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v1.1.2
        with:
          path: ${{ steps.yarn.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/website/yarn.lock')) }}

      - name: Install packages
        working-directory: ${{ env.working-directory }}
        run: yarn --frozen-lockfile

      - name: Run test
        working-directory: ${{ env.working-directory }}
        run: yarn run test
